version: '3'
services:
  backend:
    image: "node:18"
    working_dir: "/app"
    restart: "unless-stopped"
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "mysql://root:root@mysql:3306/app"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - "./:/app:delegated"
    command: "bash -c 'yarn && yarn start:dev'"
    networks:
      - "app"
    depends_on:
      - "mysql"

  mysql:
    image: "mysql:8"
    restart: "unless-stopped"
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - "app"


networks:
  app: null

volumes:
  mysql: null
